routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/login', [UserController::class, 'login'])->name('login');
Route::post('/login/auth', [UserController::class, 'loginAuth'])->name('login-auth');

Route::middleware('auth:sanctum')->group(function() {
    Route::resource('posts', PostController::class);
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
      'title',
      'description'
    ];
}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Post\StoreRequest;
use App\Http\Requests\Post\UpdateRequest;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Cache::remember('allPosts', 3600, function() {
            return Post::all();
        });
        return response()->json([
            "success"   => true,
            "message"   => "Post List",
            "data"      => $posts
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $this->authorize('create', Post::class);

        $input = $request->validated();

        $post = Post::create($input);

        return response()->json([
            "success"   => true,
            "message"   => "Post created successfully.",
            "data"      => $post
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return response()->json([
            "success"   => true,
            "message"   => "Post retrieved successfully.",
            "data"      => $post
        ]);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param
     * @param
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Post $post)
    {
        $this->authorize('update', Post::class);

        $input = $request->validated();

        $post->title        = $input['title'];
        $post->description  = $input['description'];
        $post->save();

        return response()->json([
            "success"   => true,
            "message"   => "Post updated successfully.",
            "data"      => $post
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $this->authorize('delete', Post::class);
        $post->delete();

        return response()->json([
            "success"   => true,
            "message"   => "Post deleted successfully.",
            "data"      => $post
        ]);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;
use App\Events\PostCreated;
use App\Events\PostDeleted;
use App\Events\PostUpdated;
use App\Http\Requests\Post\StoreRequest;
use App\Http\Requests\Post\UpdateRequest;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Cache::remember('allPosts', 3600, function() {
            return Post::all();
        });

        return view('post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Post::class);

        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $this->authorize('create', Post::class);

        $newPost = Post::create($request->validated());

        event(new PostCreated($newPost));

        return response()->json([
            'status'    => 'success',
            'message'   => 'Post has been created successfully',
            'route'     => route('posts.index'),
        ], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('post.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $this->authorize('update', Post::class);

        return view('post.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Post $post)
    {
        $this->authorize('update', Post::class);

        $input = $request->validated();
        $post->title        = $input['title'];
        $post->description  = $input['description'];
        $post->save();

        event(new PostUpdated($post));

        return response()->json([
            'status'    => 'success',
            'message'   => 'Post has been updated successfully',
            'route'     => route('posts.index'),
        ], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $this->authorize('delete', Post::class);

        event(new PostDeleted($post));

        $post->delete();
        return response()->json([
            'status'    => 'success',
            'message'   => 'Post has been deleted successfully',
        ], 200);

    }
}

resources/views/post/create.blade.php
@extends('layout')
@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left mb-2">
                <h2>Add Post</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('posts.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
            {{ session('status') }}
        </div>
    @endif
    <div id="errors-list"></div>
    <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data" id="postStoreForm">
        @csrf
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Post Name:</strong>
                    <input type="text" id="post-title" name="title" class="form-control" placeholder="Post Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Post Description:</strong>
                    <input type="text" id="post-description" name="description" class="form-control" placeholder="Post Description">
                </div>
            </div>
            <button type="submit" class="btn btn-primary ml-3">Submit</button>
        </div>
    </form>
    @vite(['resources/js/post.store.js'])
@endsection

resources/views/post/edit.blade.php
@extends('layout')
@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Post</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('posts.index') }}" enctype="multipart/form-data">
                    Back</a>
            </div>
        </div>
    </div>
    @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
            {{ session('status') }}
        </div>
    @endif
    <div id="errors-list"></div>
    <form action="{{ route('posts.update',$post->id) }}" method="POST" enctype="multipart/form-data" id="postUpdateForm">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Post Title:</strong>
                    <input type="text" name="title" value="{{ $post->title }}" class="form-control"
                           placeholder="Post Title">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Post Description:</strong>
                    <input type="text" name="description" class="form-control" placeholder="Post Description"
                           value="{{ $post->description }}">
                </div>
            </div>

            <button type="submit" class="btn btn-primary ml-3">Submit</button>
        </div>
    </form>
    @vite(['resources/js/post.update.js'])
@endsection

resources/views/post/index.blade.php
@extends('layout')
@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Posts List</h2>
            </div>
            @can('create', \App\Models\Post::class)
                <div class="pull-right mb-2">
                    <a class="btn btn-success" href="{{ route('posts.create') }}"> Create Post</a>
                </div>
            @endcan
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>S.No</th>
            <th>Post Title</th>
            <th width="320px">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($posts as $post)
            <tr>
                <td>{{ $post->id }}</td>
                <td>{{ $post->title }}</td>
                <td>

                    <a class="btn btn-success" href="{{ route('posts.show',$post->id) }}">Show</a>
                    @can('update', $post)
                        <a class="btn btn-primary" href="{{ route('posts.edit',$post->id) }}">Edit</a>
                    @endcan
                    @can('delete', $post)
                        <a class="btn btn-danger post-delete-form" href="#" data-url="{{ route('posts.destroy',$post->id) }}">Delete</a>
                    @endcan

                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @vite(['resources/js/post.delete.js'])
@endsection

resources/views/post/show.blade.php
@extends('layout')
@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left mb-2">
                <h2>Show Post</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('posts.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if(session('status'))
        <div class="alert alert-success mb-1 mt-1">
            {{ session('status') }}
        </div>
    @endif

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Post Title:</strong>
                <h3>{{ $post->title }}</h3>
                <p>Publish Date: {{ $post->updated_at }}</p>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Post Description:</strong>
                <p>{{ $post->description }}</p>
            </div>
        </div>

    </div>

@endsection